export const skills = [
  {
    id: "accessibility-audit",
    name: "accessibility-audit",
    description: "Revisa navegación por teclado, foco y contraste.",
    scope: "Global",
    source: "~/.agents/skills",
    tone: "blue",
    glyph: "I",
    status: "Válida",
    selected: true,
  },
  {
    id: "api-contract-review",
    name: "api-contract-review",
    description: "Valida contratos y cambios compatibles de la API.",
    scope: "Global",
    source: "~/.agents/skills",
    tone: "green",
    glyph: "•",
    status: "Válida",
    selected: true,
  },
  {
    id: "broken-frontmatter",
    name: "broken-frontmatter",
    description: "Frontmatter inválido; necesita revisión antes de usarse.",
    scope: "Global",
    source: "~/.agents/skills",
    tone: "plum",
    glyph: "■",
    status: "Inválida",
    selected: true,
  },
  {
    id: "content-check",
    name: "content-check",
    description: "Comprueba claridad, estructura y enlaces internos.",
    scope: "Global",
    source: "~/.agents/skills",
    tone: "steel",
    glyph: "│",
    status: "Válida",
    selected: false,
  },
  {
    id: "global-review",
    name: "global-review",
    description: "Review global de cambios complejos en varios repositorios.",
    scope: "Global",
    source: "~/.agents/skills",
    tone: "blue",
    glyph: "I",
    status: "Válida",
    selected: true,
  },
  {
    id: "release-notes",
    name: "release-notes",
    description: "Prepara notas de release a partir del cambio local.",
    scope: "Acme Web",
    source: "/Users/roberto/Projects/acme-web/.agents/skills",
    tone: "green",
    glyph: "■",
    status: "Válida",
    selected: true,
  },
  {
    id: "security-review",
    name: "security-review",
    description: "Identifica límites de confianza y permisos sensibles.",
    scope: "Acme Web",
    source: "/Users/roberto/Projects/acme-web/.agents/skills",
    tone: "steel",
    glyph: "•",
    status: "Válida",
    selected: false,
  },
  {
    id: "customer-research-synthesis-with-long-name",
    name: "customer-research-synthesis-with-long-name",
    description: "Sintetiza entrevistas extensas y mantiene trazabilidad hasta cada cita original.",
    scope: "Skill Forge Desktop",
    source: "/Users/roberto/Desktop/ventures/100-projects/29.skill-forge/.agents/skills",
    tone: "amber",
    glyph: "—",
    status: "Advertencia",
    selected: false,
  },
];

export const tourSlides = [
  {
    eyebrow: "Todas tus skills, por fin claras",
    title: "Entiende todas las skills que ya tienes.",
    copy: "Reúne las skills globales y de tus proyectos en un solo inventario. Ve qué hace cada una, dónde vive y en qué flujos puede ayudarte.",
    visual: "inventory",
  },
  {
    eyebrow: "Cada detalle, a mano",
    title: "Abre una skill y entiende cómo funciona.",
    copy: "Revisa sus instrucciones, archivos, origen, ámbito y estado para saber cuándo usarla y qué cambiar con confianza.",
    visual: "evidence",
  },
  {
    eyebrow: "Tus flujos, a tu manera",
    title: "Crea nuevas skills para el trabajo que repites.",
    copy: "Empieza con una estructura clara, adapta las instrucciones a tu proceso y guarda la nueva skill donde la necesites.",
    visual: "create",
  },
];

export function initialSelection() {
  return new Set(skills.filter((skill) => skill.selected).map((skill) => skill.id));
}
